### ISSUE TITLE
MUSHRA conditions are not getting randomized 

### ISSUE THREAD

**Issue by mcartwright** [interactiveaudiolab/CAQE#25]
When merging pairwise and mushra, mushra "conditions" became "condition groups" since a condition group shares a set of stimuli, and we wanted pairwise conditions to be individual pairs so they can be broken up across participants if necessary. However, this broke the randomization of the assignment of conditions. Since now in MUSHRA, there was only one condition per group. 

To fix this, we also need to randomize over groups. Therefore, we need to add in a configuration that allows this.

**Comment by jfsantos** [comment]
Any tips on how that should be fixed? I am currently using this tool and would like to randomize my MUSHRA conditions.
