### ISSUE TITLE
Default segmentation configuration has broken audio file URLs

### ISSUE THREAD

**Issue by mcartwright** [interactiveaudiolab/CAQE#29]
Currently the default segmentation configuration references audio files that were hosted externally on Dropbox. This should be changed to use testing audio files that live in the repository.

**Comment by mcartwright** [comment]
@wangsix - any chance you still have a small subset of these files around that you could add as testing files and fix the configuration? thanks!

**Comment by wangsix** [comment]
@mcartwright I am still traveling and should be able to fix this this week. Thank you.

**Comment by wangsix** [comment]
#30 was just created to solve the problem, please let me know if there is any problem.
